### ISSUE TITLE
NOTICE: plan(multiprocess) of future is deprecated

### ISSUE THREAD

**Issue by HenrikBengtsson** [JeremyGelb/geocmeans#3]
Hi. Please note that multiprocess is [deprecated since future 1.20.0 (2020-11-03)](https://future.futureverse.org/news/index.html#future-1200) and will soon be defunct:

* https://github.com/JeremyGelb/geocmeans/search?q=multiprocess

**Comment by JeremyGelb** [comment]
Noted, I will modify the code accordingly

**Comment by JeremyGelb** [comment]
It should be corrected now (version 0.2.2) and the new version will be soon on CRAN.
