### ISSUE TITLE
Examples Lack Seed Values, Leading to Inconsistent Results

### ISSUE THREAD

**Issue by Naeemkh** [JeremyGelb/geocmeans#6]
I've noticed that the examples provided do not include seed values when utilizing random processes, such as clustering. I was wondering if you expect reproducibility or not. For example, in the following examples:

https://jeremygelb.github.io/geocmeans/articles/introduction.html

While it's understood that in clustering, some variability can be acceptable, setting a seed ensures reproducibility and consistency in the results, especially for examples and tutorials. 

Thank you for your hard work on this package, and I look forward to any updates.

This issue is related to https://github.com/openjournals/joss-reviews/issues/5259 .

**Comment by JeremyGelb** [comment]
Dear @Naeemkh ,

indeed, reproductibility is an important issue. Most of the functions in `geocmeans` have an argument `seed` that can be set by the user and that will ensure that the results are identical with the same value of seed. See for example the functions [CMeans()](https://jeremygelb.github.io/geocmeans/reference/CMeans.html),  [GCMeans](https://jeremygelb.github.io/geocmeans/reference/GCMeans.html), [SFCMeans](https://jeremygelb.github.io/geocmeans/reference/SFCMeans.html), [SGFCMeans](https://jeremygelb.github.io/geocmeans/reference/SGFCMeans.html), [select_parameters](https://jeremygelb.github.io/geocmeans/reference/select_parameters.html), and [boot_group_validation](https://jeremygelb.github.io/geocmeans/reference/boot_group_validation.html). Basically, the `seed` parameter is used internally at the begining of the execution with a call to the function `set.seed`

I will add in the future a paragraph on this matter in the documentation and then close this issue.

**Comment by JeremyGelb** [comment]
A paragraph has been added here : 
https://jeremygelb.github.io/geocmeans/ and here https://jeremygelb.github.io/geocmeans/articles/introduction.html
![image](https://github.com/JeremyGelb/geocmeans/assets/46856737/a4067250-de48-43e7-a4a6-01e7b8ef0278)

Feel free to reopen the issue if you think that it should be addressed in another way.
